### PR TITLE
Added Process CPU usage into app counters

### LINKED ISSUE #60: How to monitor Process CPU usage
I am trying to figure out how to get performance a counter for CPU usage of my application. I noticed this line in [PerformanceCounter.cs](https://github.com/etishor/Metrics.NET/blob/master/Src/Metrics/PerfCounters/PerformanceCounters.cs)

````
context.Register("CPU Usage", Unit.Custom("%"), "Processor", 
 "% Processor Time", TotalInstance, tags: "cpu");
````
But it is for the whole OS. How can I get similar counter for my process? Thanks.

### PR DESCRIPTION
**Pull request by o-mdr**
This closes #60

### CODE REVIEW

**Comment by etishor** [comment]
I've manually merged this to the DEV branch - and will merge in master on release of new version. 

I've noticed the values were bigger than expected ( for % Processor Time) and according to [this article](http://social.technet.microsoft.com/wiki/contents/articles/12984.understanding-processor-processor-time-and-process-processor-time.aspx) the max value is No Cores * 100 , not just 100.

> Now this Processor time counter under the Process Object gives the amount of CPU this Process is taking individually. This value is calculated over the base line of (No of Logical CPUS * 100),  So this is going to be a calculated over a baseline of more than 100. 

For consistency with the system Processor time metric I think it is a good idea to divide the value by the number of cores.

**Comment by etishor** [comment]
New release will be available in a few days

**Comment by o-mdr** [comment]
Sounds good. However, I haven't seen CPU value > 100%. I have 8 core machine and in my test it's consuming just fractions of CPU. The test itself is doing nothing (sleeping for a few secs), so maybe that's why I didn't see spikes in CPU. 

I did thought about # Cores x 100, as it's a known thing in perf counters.

How do I make PR to your dev branch, it's second time I am trying to commit to master?..

**Comment by etishor** [comment]
I'm comparing the values with the values from Process Explorer for the specific process and if they are divided by the number of cores they match. 

Use [this guide](https://help.github.com/articles/creating-a-pull-request/) for making a PR to a specific branch. Also it is recommended that you pull the latest changes from the origin first into your local dev branch. Then create a separate branch from your dev branch, commit to it and send the PR from that separate branch to the dev branch of my repo.

**Pull request merged**
