### PR TITLE
Report metrics to elasticsearch 2.0 without dots on field names

### PR DESCRIPTION
**Pull request by andrepnh**
Quick fix for #113

### CODE REVIEW

**Comment by AmirSasson** [comment]
this is a breaking change.
what if someone doesn't use the 2.0 elastic, and have reports based on the original counter name?

**Comment by andrepnh** [comment]
Yes, I believe a good fix would be to fire a request to get the version and adjust the field name accordingly. But work on Metrics.NET probably will be done in https://github.com/PaulParau/Metrics.NET from now on.
I'll try to fix this once things settle down.

**Comment by PaulParau** [comment]
> But work on Metrics.NET probably will be done in https://github.com/PaulParau/Metrics.NET from now on.

Further work on Metrics.NET will be done in https://github.com/Recognos/Metrics.NET

**Comment by andrepnh** [comment]
Oh, I see. Thanks for pointing it out.

**Comment by PaulParau** [comment]
@AmirSasson A similar [PR](https://github.com/Recognos/Metrics.NET/pull/1) was recently accepted in the new repo (and released in the latest prerelease version of the library). This means that version 0.3.4 has the backward compatibility issue you mentioned. It would be great if you could raise an issue [there.](https://github.com/Recognos/Metrics.NET)

@andrepnh haven't thought too much about this, but wouldn't it be better to explicitly configure the naming scheme when setting the report up (i.e. through the elastic search config methods) rather than firing a request to get the elastic search version (which introduces an additional dependency)?

**Comment by andrepnh** [comment]
I've considered that too, but I thought it would be nicer to adjust the naming scheme automatically to avoid misconfiguration, since people may not be aware that there's a difference in the reporter for elasticsearch 2. 
I haven't checked out the code yet, but I was thinking that we could fire the request once when setting up the reporter and if it fails we just log and default to the current scheme, the one using dots.

**Comment by PaulParau** [comment]
OK, I understand your though process. Thanks.

**Comment by andrepnh** [comment]
I've created a [PR](https://github.com/Recognos/Metrics.NET/pull/4) with the fix I've mentioned in the new repository, so I'm closing this one.

**Pull request closed without merging**
