### PR TITLE
Implementing Merge Functionality

### PR DESCRIPTION
**Pull request by kmaragon**
We have started collecting application metrics inside of a .NET application using Metrics.NET. The application is a server application that sometimes peaks at fairly high volumes, and we collect a lot of metrics (up to 100 metrics while serving a given request, where requests generally last about 50-100 milliseconds). Most of our metrics are timing metrics. While testing the viability of the new Metrics infrastructure, in simulated high volume situations, the locking inside of Metrics.NET was causing interaction between threads, where threads would block on each other, which resulted in a non-trivial drop in throughput (and CPU usage).

While looking for a workaround, we noticed that though the documentation largely recommended using the static global objects for doing things, Metrics.NET was actually nicely written around contexts that didn't necessarily have to interact. So we designed the infrastructure such that each request got it's own private metrics context. Which worked great except at the end, while reporting metrics to the external service, the reporter infrastructure expected the global object. But attaching contexts to the global object become problematic because metrics of the same type for the same thing for parallel requests were being represented separately.

To handle this, we set up the concept of a "Merge," where different MetricsContexts can be merged together logically to appear as though the parallel requests were serial as they are reported. Then, after the requests are processed, the associated contexts are placed onto a merge queue. A separate background thread picks up the contexts off of the queue and merges them into the global one. This is the patch that we used to enable the Merge.

There were some changes in some places to preserve a bit more history as to enable the appropriate replay functionality.

Thank you so much for this great Contribution!

### CODE REVIEW

**Comment by etishor** [comment]
Wow this is a big PR. Thanks for the effort. I will most probably merge it in the next few days after I'll get a change to review it. 

Thanks again.

**Comment by etishor** [comment]
Thank you again for the effort. I will merge this for now as the "context merging" functionality makes sense, but I still want to test and maybe re-think some bits of it. Depending on external factors (like snow forecast and ski condition) It might take one or more weeks to finalize and push a new release. If you need it I could publish a nuget with a pre-release version containing this changes. 

I never managed to measure any noticeable impact on highly concurrent applications. I know there is an impact and I'm almost certain there are cases where the impact is visible I just have not hit them yet.  In a production app I have timers measuring operations that execute concurrently and that take 3-5 ms each and nothing changes if I remove the timers. It is true that I don't have even close to ~100 timers in the context of one request. That is a scenario I would really like to test.

Lately in my day job I had to do a lot of low level performance optimizations - and learned a lot doing it - and I was thinking of doing a "performance iteration" over the metrics library. Some of the main goals are: 
* avoid any memory allocation on metrics collection path ( and minimize allocations on metrics reporting path)
* minimize the amount of sharing of instance between threads (see point below)
* implement/use [hdrhistogram](https://github.com/HdrHistogram/HdrHistogram) - which seems to be extreamly efficent- as an option or maybe even as default histogram for timers
* maintain simple and clear public api for most common cases (this is very important to me)

Related to instance sharing between threads. I was thinking that (at least in theory) it should be possible to collect metrics without any kind of sharing between threads. Conceptually the backing store for the metrics could be thread static and no locking/interlocked operations should be needed to update the internal structures. This should not even be very hard to implement. The problem now becomes aggregating and reporting. A separate thread could go over the structures where the metrics are collected and with minimal interference would collect the values, aggregate them and pass them to the reporting implementations. This is probably a generalization of what you achieved with the context merging. I'll play a bit with a possible implementation and come back with updates.

It would be very useful if you could run a contention profiling session on the code and environment where you noticed the impact of timers. Maybe there is something more fundamental causing the issues. 

Thanks,
Iulian

PS: i've noticed you also are a contributor/author to the SignalFx adapter. While I know very little about SignalFx i've noticed the concept of "dimensions". Let me know if you think support for metrics "metadata" could be improved of if you have any concrete ideas on how that could be done.

**Comment by kmaragon** [comment]
No rush on the new release. It seems like a lot of where you are going would moot the need for the merge functionality in our use case (or potentially expand on it) - although it still might be useful for other less performance-based and more logical-based requirements. But it seems like your train of thought went right through the limitations we ran into while trying to report via SignalFx with thread-specific contexts. And that is precisely where context merging came from, as you concluded.

I will see what I can do regarding a contention profiling session. Perhaps you could give some advice on tooling. It's always hard doing it the manual way (which is all I did) since it's one of those things where observation affects the outcome.

I think the big reason that SignalFx wrote their own custom Context extension was to differentiate metrics not just by name but by "dimensions." So metadata wouldn't be a bad idea - but the only logical role it would need to play to support the SignalFx use case is to index (and report) the metrics as separate units for each unique combination of metadata.

Thanks for the merge, and thanks again even more for building this. Now if only I can find something as friendly but also as thoroughly implemented in C++, my life will be much more complete :laughing:

**Comment by etishor** [comment]
For contention profiling the Visual Studio profiler is good enough most of the times. In VS 2013 go to "Analyse" => "Performance Diagnostics" => select "Performance Wizard" & profiling target=> in the wizard select "Resource contention data (concurrency)". You will have to try with different scenarios until the data starts to make sense. CPU profiling can also show possible bottlenecks which are not obvious from code.

**Pull request merged**
